edition                      = "2024"
max_width                    = 80
tab_spaces                   = 2
use_small_heuristics         = "Default"
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true
format_generated_files       = true
use_field_init_shorthand     = true
imports_granularity          = "Module"
reorder_imports              = true
reorder_impl_items           = true
match_arm_leading_pipes      = "Preserve"
enum_discrim_align_threshold = 24
wrap_comments                = true
